scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    tiles.setWallAt(tiles.getTileLocation(9, 9), false)
    tiles.setTileAt(tiles.getTileLocation(9, 9), sprites.castle.tilePath5)
    tiles.setWallAt(tiles.getTileLocation(9, 10), false)
    tiles.setTileAt(tiles.getTileLocation(9, 10), sprites.castle.tilePath5)
    tiles.setWallAt(tiles.getTileLocation(9, 11), false)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairLarge, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`nivel2`)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestOpen, function (sprite, location) {
    game.splash("Este cofre ya ha sido saqueado")
    tiles.setTileAt(tiles.getTileLocation(1, 1), sprites.castle.tilePath5)
})
let prota = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(prota)
scene.cameraFollowSprite(prota)
tiles.setCurrentTilemap(tilemap`nivel1`)
